Updated LDBC SNB Enhancer version
SolidBench/SolidBench.js pull request #6
Opened 2023-01-30 14:19 UTC by Sindhu-Vasireddy

2023-01-30 14:24 UTC, rubensworks requested changes

2023-01-30 14:24 UTC, rubensworks commented on lib/Generator.ts
> +    // eslint-disable-next-line unicorn/prefer-string-replace-all
Perhaps we can just apply the suggested linter enchancement :-)

2023-01-30 14:24 UTC, rubensworks commented on templates/enhancer-config-pod.json
> +}
There's a missing newline at the end of this file. Could you add one? Then git will just see this as a file rename, without differences.

2023-01-30 15:45 UTC, Sindhu-Vasireddy commented
@rubensworks I have updated it now. Please have a look.

2023-01-31 07:51 UTC, merged

2023-01-31 07:52 UTC, rubensworks commented
Thanks, released as 1.5.0.